### ISSUE TITLE
Week 2 - Task list and issues

### ISSUE THREAD

**Issue by MacyChan** [UBC-MDS/pylyrics#28]
[Milestone 2](https://pages.github.ubc.ca/mds-2021-22/DSCI_524_collab-sw-dev_students/materials/assignments/milestone2.html)

**Python** (by Thur)
- [x] #31
- [x] #32
- [x] #33
- [x] #34

**Cross-Checking**
- [x] #35
- [x] #36
- [x] #37
- [x] #38
e.g. Manju, Abhiket will check the function `plot_cloud`  written by Atan

==================Following has added to R project=========================
[rlyrics](https://github.com/UBC-MDS/rlyrics)
**R** (by Thur)
- Milestone Submission - Abhiket
- Kanban Setup + covert issue - Macy
- Main brach protection setup - Artan
- Create project structure - Artan
- Manage issues - Macy
- README.md - Manju
      CONTRIBUTORS
      summary (Overview)
      bulleted list of the functions
      Python ecosystem
      Features
      Dependency
      usage
      CONDUCT.md
      CONTRIBUTING.md

**Function specifications (4 .R)**
- download_data - Manju
- extract_lyrics - Macy
- clean_text - Abhiket
- plot_cloud - Artan

**Comment by MacyChan** [comment]
- 

- [ ] Add {key: value} example on doctoring Artan
- [ ] ReadME usage download_data input -Manju
- [ ] Remove ReadMe Usage pylyrics
- [ ] Functions ReadMe clean_text -> clean_text
